logging:
  config: classpath:log4j2.xml

mybatis:
  type-aliases-package: com.liyulin.shading.jdbc.demo.entity
  mapper-locations: classpath:mapper/*.xml

jasypt:
  encryptor:
    password: 123456

mapper:
  not-empty: true
  identity: MYSQL
spring:  shardingsphere:    datasource:      names: product
      product:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo_log?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: ENC(Ell/BrCjyLFI0+iZgPqo6w==)
        password: ENC(Aq90bjkofJr0svNO4mtFfw==)
    props:
      sql.show: true
    sharding:      default-data-source-name: ${sharding.jdbc.datasource.names}
      tables:
        t_api_log: 
          table-strategy:
            standard: 
              sharding-column: f_sys_add_time
              precise-algorithm-class-name: com.liyulin.shading.jdbc.algorithm.WeekPreciseShardingAlgorithm
              range-algorithm-class-name: com.liyulin.shading.jdbc.algorithm.WeekRangeShardingAlgorithm