logging:
  config: classpath:log4j2.xml

mybatis:
  type-aliases-package: com.liyulin.shading.jdbc.demo.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  not-empty: true
  identity: MYSQL
  
sharding:  jdbc:
    datasource:      names: product
      product:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo_product?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    config:
      sharding:        default-data-source-name: ${sharding.jdbc.datasource.names}
        tables:
          t_product_info: 
            table-strategy:              standard: 
                sharding-column: f_sys_add_time
                precise-algorithm-class-name: com.liyulin.shading.jdbc.demo.algorithm.WeekPreciseShardingAlgorithm      props:        sql.show: true